"""Generate tests.sh — the manual-verification script.

DESIGN NOTE / SAFETY: this generator is EMIT-ONLY by default. It writes a shell
script and stops. Nothing is executed unless the operator passes --execute,
which is a separate, explicit, non-recursive opt-in that runs the script under
bash with a confirmation gate.

Rationale: `content query` against an exported provider is data exfiltration if
the provider is misconfigured, and a batch run over a directory of APKs would
fire every generated command at every app on the device. Generation is a
documentation aid; execution is a deliberate human decision.
"""
from __future__ import annotations

import os
import re
import stat

BANNER = r"""#!/data/data/com.termux/files/usr/bin/bash
# tests.sh — generated by apk-surface. REVIEW EVERY LINE BEFORE RUNNING.
#
# These commands talk to the target app's exported components. Against an app you
# are not authorized to test, this is exploitation tooling, not research.
#
# The target package and the app may need to be installed first:
#     termux-open <path-to-app.apk>
#
# Everything here is a HYPOTHESIS from static analysis. A crash or an exception
# confirms nothing on its own; check whether the data you got back was meant
# for you.
set -uo pipefail

PKG="__PKG__"
echo "target: $PKG"
echo "is it installed?"
pm path "$PKG" || echo "  not installed — install the APK first"
echo
"""


def _pkg_of(name: str, pkg: str) -> str:
    if not name:
        return ""
    if name.startswith("."):
        return pkg + name
    if "." not in name:
        return f"{pkg}.{name}"
    return name


def generate(r: dict, path: str) -> str:
    pkg = r.get("package", "")
    comps = r.get("components", [])
    L: list[str] = [BANNER.replace("__PKG__", pkg or "com.example.app")]

    acts = [c for c in comps if c["type"] in ("activity", "activity-alias")
            and c.get("exported")]
    svcs = [c for c in comps if c["type"] == "service" and c.get("exported")]
    recvs = [c for c in comps if c["type"] == "receiver" and c.get("exported")]
    provs = [c for c in comps if c["type"] == "provider" and c.get("exported")]

    L.append('# ---------------------------------------------------------------- activities')
    if acts:
        for c in acts:
            n = c["name"]
            L.append(f'echo "--- launch {n}"')
            L.append(f'am start -W -n {pkg}/{n}')
            L.append(f'# type confusion: extras whose type does not match the expectation')
            L.append(f'am start -W -n {pkg}/{n} --ei extra_int 1 --es extra_str x '
                     f'--ez extra_bool true')
            L.append(f'# direct component launch, bypassing any launcher routing:')
            L.append(f'am start -W -n {pkg}/{n} --es probe 1')
            L.append("")
    else:
        L.append('echo "(no exported activities)"\n')

    L.append('# ---------------------------------------------------------------- services')
    if svcs:
        for c in svcs:
            L.append(f'echo "--- start service {c["name"]}"')
            L.append(f'am start-foreground-service -n {pkg}/{c["name"]} 2>/dev/null '
                     f'|| am startservice -n {pkg}/{c["name"]}')
            L.append("")
    else:
        L.append('echo "(no exported services)"\n')

    L.append('# ---------------------------------------------------------------- receivers')
    if recvs:
        for c in recvs:
            acts_used = sorted({a for f in c.get("intent_filters", [])
                                for a in f.get("actions", [])})
            for a in (acts_used or ["com.example.PROBE"]):
                L.append(f'echo "--- broadcast {a} -> {c["name"]}"')
                L.append(f'am broadcast -a {a} -n {pkg}/{c["name"]} --es probe 1')
            L.append("")
    else:
        L.append('echo "(no exported receivers)"\n')

    L.append('# ---------------------------------------------------------------- providers')
    if provs:
        for c in provs:
            auth = c.get("authorities")
            if not auth:
                L.append(f'# provider {c["name"]} declares no authorities — cannot form a content URI')
                continue
            base = f"content://{auth}"
            L.append(f'echo "--- query {c["name"]}"')
            L.append(f'content query --uri "{base}" 2>&1 | head -40')
            L.append(f'# path traversal attempt (ZipSlip-equivalent at the content layer)')
            L.append(f'content query --uri "{base}/../databases/app.db" 2>&1 | head -20')
            L.append(f'# grantUriPermissions with a content:// URI from a foreign app is the real test;')
            L.append(f'# this only tells you whether the shell identity is allowed.')
            L.append("")
    else:
        L.append('echo "(no exported providers)"\n')

    L.append('# ---------------------------------------------------------------- deep links')
    links = r.get("custom_schemes", []) + r.get("app_links", [])
    if links:
        for lk in links:
            scheme = lk["scheme"]
            host = lk.get("host") or ""
            if scheme in ("http", "https"):
                url = f"{scheme}://{host or 'example.invalid'}/"
            else:
                url = f"{scheme}://{host or 'probe'}/payload?x=1"
            L.append(f'echo "--- deeplink {url}"')
            L.append(f'am start -W -a android.intent.action.VIEW -d "{url}" {pkg}')
        L.append("")
    else:
        L.append('echo "(no deep links)"\n')

    L.append('# ---------------------------------------------------------------- misc probes')
    L.append('echo "--- cloud endpoints (verify live, keys alone are N/A)"')
    L.append(f'# firebase: curl -s https://<db>.firebaseio.com/.json | head -20  (must 401/404)')
    L.append(f'# s3: aws s3 ls s3://<bucket> --no-sign-request; curl -s https://<bucket>.s3.amazonaws.com/ | head -20')
    L.append(f'# maps/geofeed keys in meta-data: call the API as the key, check referrer restrictions')
    L.append("")
    L.append('echo "--- backup / data extraction"')
    L.append(f'# allowBackup on a debuggable or debug-signed build:')
    L.append(f'#   adb backup -apk -shared com.{pkg}  (older platforms)')
    L.append(f'# On API 31+ use the device OEM backup agent; check the dataExtractionRules instead.')
    L.append("")
    L.append('echo "--- cleartext / network config"')
    L.append(f'settings get global http_proxy   # if a proxy is set, is it trusted?')
    L.append("")
    L.append("echo 'done'")

    text = "\n".join(L) + "\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP)
    return path
